In [15]:
import numpy as np

n = 100
p = 8
eps = 1e-14
max_iter = 10000

def generate_diagonally_dominant_matrix(n, min_val=1, max_val=10):
    A = np.random.randint(min_val, max_val + 1, size=(n, n))

    for i in range(n):
        row_sum = np.sum(np.abs(A[i])) - np.abs(A[i][i])
        A[i][i] = row_sum + np.random.randint(1, 5)

    return A


A = generate_diagonally_dominant_matrix(n)

X = np.full((n, 1), p)

B = A @ X
print('Матриця А')
print(A)
print("Матриця B (результат множення A на X) перші 5 рядочків:")
print(B[:5])
print("Матриця B (результат множення A на X) останні 5 рядочків:")
print(B[-5:])
print("X")
print(X)
np.savetxt("matrix_A.txt", A, fmt="%d")
np.savetxt("vector_B.txt", B, fmt="%d")

Матриця А
[[518   9   7 ...   5   2   8]
 [ 10 544   7 ...   2   5  10]
 [  2   1 519 ...   3   2   6]
 ...
 [  7   2   4 ... 484   2   6]
 [ 10   8   5 ...   2 549   2]
 [  8   2   5 ...   8   3 527]]
Матриця B (результат множення A на X) перші 5 рядочків:
[[8264]
 [8688]
 [8280]
 [8408]
 [9008]]
Матриця B (результат множення A на X) останні 5 рядочків:
[[8696]
 [9040]
 [7728]
 [8752]
 [8400]]
X
[[8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]
 [8]]


In [16]:
def vector_norm(X):
    return np.max(np.abs(X))


def matrix_norm(A):
    return np.max(np.sum(np.abs(A), axis=1))


def multiply_matrix_vector(A, X):
    return A @ X
    

print("Норма матриці A:", matrix_norm(A))
print("Норма вектора X:", matrix_norm(B))
print("Добуток матриці на вектор перші 5: ", multiply_matrix_vector(A, X)[:5])
print("Добуток матриці на вектор останні 5: ", multiply_matrix_vector(A, X)[-5:])


Норма матриці A: 1247
Норма вектора X: 9976
Добуток матриці на вектор перші 5:  [[8264]
 [8688]
 [8280]
 [8408]
 [9008]]
Добуток матриці на вектор останні 5:  [[8696]
 [9040]
 [7728]
 [8752]
 [8400]]


In [17]:
import numpy as np


def simple_iteration(A, B, epsilon=1e-5, max_iter=1000, X_init=None):
    n = len(B)

    if X_init is None:
        X = np.zeros((n, 1))
    else:
        X = np.full((n, 1), X_init)

    print("Початковий вектор X:")
    print(X[:5])

    tau = 1 / matrix_norm(A)

    for iteration in range(1, max_iter + 1):
        X_new = X - tau * (multiply_matrix_vector(A, X) - B)
        diff = X_new - X
        if vector_norm(diff) < epsilon:
            print(f"Збіжність досягнута за {iteration} ітерацій.")
            return X_new
        X = X_new

    print("Максимальна кількість ітерацій досягнута.")
    return X


X_init = 20
X_result = simple_iteration(A, B, X_init=X_init)
print("Розв'язок X перші 5:")
print(X_result[:5])
print("Розв'язок X останні 5:")
print(X_result[-5:])


Початковий вектор X:
[[20]
 [20]
 [20]
 [20]
 [20]]
Збіжність досягнута за 25 ітерацій.
Розв'язок X перші 5:
[[8.00000127]
 [7.99999832]
 [7.99999797]
 [8.0000018 ]
 [7.99999982]]
Розв'язок X останні 5:
[[7.99999917]
 [7.99999816]
 [8.00001145]
 [8.00000176]
 [7.99999916]]


In [18]:
def seidel_method(A, B, epsilon=1e-5, max_iter=1000):
    n = len(B)
    X = np.full((n, 1),100)

    for iteration in range(1, max_iter + 1):
        X_new = np.copy(X)

        for i in range(n):
            sum1 = np.dot(A[i, :i], X_new[:i].flatten())
            sum2 = np.dot(A[i, i + 1:], X[i + 1:].flatten())
            X_new[i] = (B[i] - sum1 - sum2) / A[i, i]

        diff = X_new - X
        if vector_norm(diff) < epsilon:
            print(f"Збіжність досягнута за {iteration} ітерацій.")
            return X_new

        X = X_new

    print("Максимальна кількість ітерацій досягнута.")
    return X


X_result = seidel_method(A, B)
print("Розв'язок X")
print(X_result[:5])


Збіжність досягнута за 6 ітерацій.
Розв'язок X
[[8]
 [8]
 [8]
 [8]
 [8]]


In [19]:
def jacobi_method(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = np.zeros_like(X)
        for i in range(n):
            s = np.dot(A[i, :i], X[:i]) + np.dot(A[i, i+1:], X[i+1:])
            X_new[i] = (B[i] - s) / A[i, i]
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

In [20]:

X_jac, it_jac = jacobi_method(A, B)

print("Перші 5 елементів розв'язку методом Якобі:")
print(X_jac[:5])
print(f"Кількість ітерацій: {it_jac}")


Перші 5 елементів розв'язку методом Якобі:
[[8.]
 [8.]
 [8.]
 [8.]
 [8.]]
Кількість ітерацій: 10000


In [21]:
import numpy as np

# Константи
n = 100
p = 8
eps = 1e-14
max_iter = 10000

# Генерація матриці з діагональним переважанням
def generate_diagonally_dominant_matrix(n, min_val=1, max_val=10):
    A = np.random.randint(min_val, max_val + 1, size=(n, n)).astype(float)
    for i in range(n):
        row_sum = np.sum(np.abs(A[i])) - np.abs(A[i][i])
        A[i][i] = row_sum + np.random.uniform(1, 5)
    return A

# Норми та допоміжні функції
def vector_norm(X):
    return np.max(np.abs(X))

def matrix_norm(A):
    return np.max(np.sum(np.abs(A), axis=1))

def multiply_matrix_vector(A, X):
    return A @ X

# Метод Якобі
def jacobi_method(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = np.zeros_like(X)
        for i in range(n):
            s = np.dot(A[i, :i], X[:i]) + np.dot(A[i, i+1:], X[i+1:])
            X_new[i] = (B[i] - s) / A[i, i]
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

# Метод Зейделя
def seidel_method(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = np.copy(X)
        for i in range(n):
            s1 = np.dot(A[i, :i], X_new[:i])
            s2 = np.dot(A[i, i+1:], X[i+1:])
            X_new[i] = (B[i] - s1 - s2) / A[i, i]
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

# Метод простої ітерації
def simple_iteration(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    tau = 1.0 / matrix_norm(A)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = X - tau * (multiply_matrix_vector(A, X) - B)
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

A = generate_diagonally_dominant_matrix(n)
X_true = np.full((n, 1), 2.5)
B = multiply_matrix_vector(A, X_true)

X_sit, it_sit = simple_iteration(A, B)
X_jac, it_jac = jacobi_method(A, B)
X_sei, it_sei = seidel_method(A, B)

errors = {
    'Проста ітерація': np.max(np.abs(X_sit - X_true)),
    'Якобі': np.max(np.abs(X_jac - X_true)),
    'Зейделя': np.max(np.abs(X_sei - X_true))
}

print("Результати розв'язання системи лінійних рівнянь (Ax = B):\n")

print("Метод простої ітерації:")
print(f"  Кількість ітерацій: {it_sit}")
print(f"  Максимальна похибка: {errors['Проста ітерація']:.2e}\n")

print("Метод Якобі:")
print(f"  Кількість ітерацій: {it_jac}")
print(f"  Максимальна похибка: {errors['Якобі']:.2e}\n")

print("Метод Зейделя:")
print(f"  Кількість ітерацій: {it_sei}")
print(f"  Максимальна похибка: {errors['Зейделя']:.2e}\n")

print("Вектор істинного розв'язку (перші 5 елементів):")
print(X_true[:5].flatten())

print("\nВектор, знайдений методом простої ітерації (перші 5 елементів):")
print(X_sit[:5].flatten())

print("\nВектор, знайдений методом Якобі (перші 5 елементів):")
print(X_jac[:5].flatten())

print("\nВектор, знайдений методом Зейделя (перші 5 елементів):")
print(X_sei[:5].flatten())


Результати розв'язання системи лінійних рівнянь (Ax = B):

Метод простої ітерації:
  Кількість ітерацій: 65
  Максимальна похибка: 1.42e-14

Метод Якобі:
  Кількість ітерацій: 5969
  Максимальна похибка: 4.88e-15

Метод Зейделя:
  Кількість ітерацій: 23
  Максимальна похибка: 2.22e-15

Вектор істинного розв'язку (перші 5 елементів):
[2.5 2.5 2.5 2.5 2.5]

Вектор, знайдений методом простої ітерації (перші 5 елементів):
[2.5 2.5 2.5 2.5 2.5]

Вектор, знайдений методом Якобі (перші 5 елементів):
[2.5 2.5 2.5 2.5 2.5]

Вектор, знайдений методом Зейделя (перші 5 елементів):
[2.5 2.5 2.5 2.5 2.5]
