In [53]:
import numpy as np

n = 100
p = 8
eps = 1e-14
max_iter = 10000

def generate_diagonally_dominant_matrix(n, min_val=1, max_val=10):
    A = np.random.randint(min_val, max_val + 1, size=(n, n))

    for i in range(n):
        row_sum = np.sum(np.abs(A[i])) - np.abs(A[i][i])
        A[i][i] = row_sum + np.random.randint(1, 5)

    return A


A = generate_diagonally_dominant_matrix(n)

X = np.full((n, 1), p)

B = A @ X
print('Матриця А')
print(A)
print("Матриця B")
print(B)
print("X")
print(X)
np.savetxt("matrix_A.txt", A, fmt="%d")

np.savetxt("vector_B.txt", B, fmt="%d")

Матриця А
[[549   7   7 ...   4   3   1]
 [ 10 577   5 ...  10   7   4]
 [  8   6 484 ...   2   3   8]
 ...
 [  1   1   4 ... 557   1   2]
 [  7   9   8 ...   1 547   2]
 [  5   5   6 ...   3   2 519]]
Матриця B
[[8776]
 [9216]
 [7728]
 [8568]
 [7920]
 [8064]
 [8640]
 [8896]
 [8784]
 [8304]
 [8904]
 [9024]
 [8992]
 [8912]
 [8688]
 [8928]
 [8120]
 [8760]
 [8288]
 [8200]
 [9088]
 [8552]
 [9248]
 [8264]
 [8128]
 [8368]
 [8928]
 [8256]
 [8216]
 [8528]
 [8688]
 [8224]
 [8152]
 [8312]
 [8528]
 [9288]
 [7640]
 [9696]
 [9352]
 [7648]
 [8648]
 [8848]
 [8920]
 [8912]
 [8376]
 [8896]
 [9224]
 [8864]
 [8960]
 [9224]
 [8192]
 [8424]
 [8568]
 [8960]
 [8616]
 [9560]
 [9152]
 [8752]
 [8864]
 [8728]
 [9240]
 [8328]
 [8216]
 [8080]
 [9024]
 [8096]
 [8216]
 [8744]
 [9280]
 [8272]
 [8504]
 [8816]
 [8864]
 [8736]
 [8712]
 [9232]
 [8112]
 [8448]
 [8616]
 [7888]
 [9152]
 [9064]
 [8920]
 [8912]
 [8304]
 [8056]
 [8488]
 [8920]
 [8096]
 [8208]
 [8928]
 [8800]
 [8736]
 [8872]
 [8744]
 [9088]
 [8592]
 [8904]
 [87

In [54]:
def vector_norm(X):
    return np.max(np.abs(X))


def matrix_norm(A):
    return np.max(np.sum(np.abs(A), axis=1))


def multiply_matrix_vector(A, X):
    return A @ X


print("Норма матриці A:", matrix_norm(A))
print("Норма вектора B:", vector_norm(B))
print("Добуток матриці на веткор: ", multiply_matrix_vector(A, X))

Норма матриці A: 1212
Норма вектора B: 9696
Добуток матриці на веткор:  [[8776]
 [9216]
 [7728]
 [8568]
 [7920]
 [8064]
 [8640]
 [8896]
 [8784]
 [8304]
 [8904]
 [9024]
 [8992]
 [8912]
 [8688]
 [8928]
 [8120]
 [8760]
 [8288]
 [8200]
 [9088]
 [8552]
 [9248]
 [8264]
 [8128]
 [8368]
 [8928]
 [8256]
 [8216]
 [8528]
 [8688]
 [8224]
 [8152]
 [8312]
 [8528]
 [9288]
 [7640]
 [9696]
 [9352]
 [7648]
 [8648]
 [8848]
 [8920]
 [8912]
 [8376]
 [8896]
 [9224]
 [8864]
 [8960]
 [9224]
 [8192]
 [8424]
 [8568]
 [8960]
 [8616]
 [9560]
 [9152]
 [8752]
 [8864]
 [8728]
 [9240]
 [8328]
 [8216]
 [8080]
 [9024]
 [8096]
 [8216]
 [8744]
 [9280]
 [8272]
 [8504]
 [8816]
 [8864]
 [8736]
 [8712]
 [9232]
 [8112]
 [8448]
 [8616]
 [7888]
 [9152]
 [9064]
 [8920]
 [8912]
 [8304]
 [8056]
 [8488]
 [8920]
 [8096]
 [8208]
 [8928]
 [8800]
 [8736]
 [8872]
 [8744]
 [9088]
 [8592]
 [8904]
 [8736]
 [8280]]


In [55]:
import numpy as np


def simple_iteration(A, B, epsilon=1e-5, max_iter=1000, X_init=None):
    n = len(B)

    if X_init is None:
        X = np.zeros((n, 1))
    else:
        X = np.full((n, 1), X_init)

    print("Початковий вектор X:")
    print(X)

    tau = 1 / matrix_norm(A)

    for iteration in range(1, max_iter + 1):
        X_new = X - tau * (multiply_matrix_vector(A, X) - B)
        diff = X_new - X
        if vector_norm(diff) < epsilon:
            print(f"Збіжність досягнута за {iteration} ітерацій.")
            return X_new
        X = X_new

    print("Максимальна кількість ітерацій досягнута.")
    return X


X_init = 20
X_result = simple_iteration(A, B, X_init=X_init)
print("Розв'язок X:")
print(X_result)


Початковий вектор X:
[[20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]]
Збіжність досягнута за 25 ітерацій.
Розв'язок X:
[[7.99999817]
 [7.9999992 ]
 [8.00000786]
 [7.99999972]
 [8.00000281]
 [8.00000326]
 [7.99999915]
 [7.99999879]
 [7.99999948]
 [8.00000027]
 [7.99999877]
 [7.99999916]
 [7.99999932]
 [7.99999897]
 [7.99999829]
 [7.99999976]
 [7.99999976]
 [7.99999766]
 [7.99999925]
 [8.00000302]
 [7.99999868]
 [7.99999789]
 [7.99999966]
 [7.999

In [56]:
def seidel_method(A, B, epsilon=1e-5, max_iter=1000):
    n = len(B)
    X = np.full((n, 1),100)

    for iteration in range(1, max_iter + 1):
        X_new = np.copy(X)

        for i in range(n):
            sum1 = np.dot(A[i, :i], X_new[:i].flatten())
            sum2 = np.dot(A[i, i + 1:], X[i + 1:].flatten())
            X_new[i] = (B[i] - sum1 - sum2) / A[i, i]

        diff = X_new - X
        if vector_norm(diff) < epsilon:
            print(f"Збіжність досягнута за {iteration} ітерацій.")
            return X_new

        X = X_new

    print("Максимальна кількість ітерацій досягнута.")
    return X


X_result = seidel_method(A, B)


Збіжність досягнута за 6 ітерацій.


In [57]:
def jacobi_method(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = np.zeros_like(X)
        for i in range(n):
            s = np.dot(A[i, :i], X[:i]) + np.dot(A[i, i+1:], X[i+1:])
            X_new[i] = (B[i] - s) / A[i, i]
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

In [61]:

X_jac, it_jac = jacobi_method(A, B)

# Вивід результатів
errors = {
    'Errors': X_jac
}
iterations = {

    "Якобі": it_jac,
}

errors, iterations

({'Errors': array([[2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5],
         [2.5]

In [59]:
import numpy as np

# Константи
n = 100
p = 8
eps = 1e-14
max_iter = 10000

# Генерація матриці з діагональним переважанням
def generate_diagonally_dominant_matrix(n, min_val=1, max_val=10):
    A = np.random.randint(min_val, max_val + 1, size=(n, n)).astype(float)
    for i in range(n):
        row_sum = np.sum(np.abs(A[i])) - np.abs(A[i][i])
        A[i][i] = row_sum + np.random.uniform(1, 5)
    return A

# Норми та допоміжні функції
def vector_norm(X):
    return np.max(np.abs(X))

def matrix_norm(A):
    return np.max(np.sum(np.abs(A), axis=1))

def multiply_matrix_vector(A, X):
    return A @ X

# Метод Якобі
def jacobi_method(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = np.zeros_like(X)
        for i in range(n):
            s = np.dot(A[i, :i], X[:i]) + np.dot(A[i, i+1:], X[i+1:])
            X_new[i] = (B[i] - s) / A[i, i]
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

# Метод Зейделя
def seidel_method(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = np.copy(X)
        for i in range(n):
            s1 = np.dot(A[i, :i], X_new[:i])
            s2 = np.dot(A[i, i+1:], X[i+1:])
            X_new[i] = (B[i] - s1 - s2) / A[i, i]
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

# Метод простої ітерації
def simple_iteration(A, B, epsilon=eps, max_iter=max_iter):
    n = len(B)
    tau = 1.0 / matrix_norm(A)
    X = np.ones((n, 1))
    iterations = 0

    for _ in range(max_iter):
        X_new = X - tau * (multiply_matrix_vector(A, X) - B)
        iterations += 1
        if vector_norm(X_new - X) < epsilon:
            return X_new, iterations
        X = X_new
    return X, iterations

# Генерація даних
A = generate_diagonally_dominant_matrix(n)
X_true = np.full((n, 1), 2.5)
B = multiply_matrix_vector(A, X_true)

# Розв’язання
X_sit, it_sit = simple_iteration(A, B)
X_jac, it_jac = jacobi_method(A, B)
X_sei, it_sei = seidel_method(A, B)

# Вивід результатів
errors = {
    "Проста ітерація": vector_norm(X_sit - X_true),
    "Якобі": vector_norm(X_jac - X_true),
    "Зейделя": vector_norm(X_sei - X_true),
}
iterations = {
    "Проста ітерація": it_sit,
    "Якобі": it_jac,
    "Зейделя": it_sei,
}

errors, iterations


({'Проста ітерація': np.float64(1.199040866595169e-14),
  'Якобі': np.float64(3.108624468950438e-14),
  'Зейделя': np.float64(3.9968028886505635e-15)},
 {'Проста ітерація': 65, 'Якобі': 10000, 'Зейделя': 23})